---
- name: Bring up the instances in the first zone
  gce:
    instance_names: "{{ names_zonea }}" 
    machine_type: "{{ machine_type }}" 
    image: "{{ image }}" 
    zone: "{{ zonea }}" 
    project_id: "{{ project_id }}" 
    credentials_file: "{{ credentials_file }}" 
    service_account_email: "{{ service_account_email }}" 
  register: gcea

- name: Bring up the instances in the second zone
  gce:
    instance_names: "{{ names_zoneb }}" 
    machine_type: "{{ machine_type }}" 
    image: "{{ image }}" 
    zone: "{{ zoneb }}" 
    project_id: "{{ project_id }}" 
    credentials_file: "{{ credentials_file }}" 
    service_account_email: "{{ service_account_email }}" 
  register: gceb

- name: Wait for SSH for instances in first zone
  wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=60
  with_items: "{{ gcea.instance_data }}" 

- name: Save host data for first zone
  add_host: hostname={{ item.public_ip }} groupname=gce_instances_ips
  with_items: "{{ gcea.instance_data }}" 

- name: Wait for SSH for instances in second zone
  wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=60
  with_items: "{{ gceb.instance_data }}" 

- name: Save host data for second zone
  add_host: hostname={{ item.public_ip }} groupname=gce_instances_ips
  with_items: "{{ gceb.instance_data }}"
... 
