---
- name: Run apt-get update
  apt:
    name: "*"
    state: latest

- name: Install python-apt via command module
  apt:
    name: python-apt
    state: latest

- name: Install apache on instances
  apt: 
   name: apache2 
   state: latest

- name: State start apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Create custom index.html
  template: 
    src: index.html.j2
    dest: /var/www/index.html

- name: Set file stats on index.html
  file: 
    path: /var/www/index.html 
    owner: root 
    group: root
    mode: 0644

- name: Deploy modified apache conf
  copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: 0644

- name: Enable mod_headers
  file:
    path: /etc/apache2/mods-enabled/headers.load
    src: /etc/apache2/mods-available/headers.load
    state: link

- name: Restart apache
  service:
    name: apache2
    state: restarted
...
